### ISSUE TITLE
Lack of error handling / status messages

### ISSUE THREAD

**Issue by kekukui** [tmcw/clone-pull-requests#1]
Is this API still supported?  I see no indication of success or failure, and nothing was accomplished when valid arguments were provided.  Also, is there a document which describes how to do this manually?

**Comment by tmcw** [comment]
This was made to solve a particular problem, to clone pull requests between repositories. It does log on progress and [on completion](https://github.com/tmcw/clone-pull-requests/blob/master/index.js#L71).
